slug = "backup"
title = "Backup"
author = "Rory"
value = 25
description = """This [file](backup) won most secure of the year back in its time"""
tags = ["overflow2"]
files = ["backup"]
flag = "flag{c4ts_4nd_c0ffee}"
enabled = true
