slug = "lost_riddle_1"
title = "First Lost Riddle"
author = "Luke"
value = 20
description = """I lost my riddles but still remember the answers somehow. Do you think you can figure them out without the riddles? Binary [here](lost_riddles), limited source [here](source.c)."""
tags = ["overflow"]
files = ["lost_riddles", "source.c"]
flag = "flag{f0u1_t4rn15sh3d}"
enabled = true
