slug = "need-for-fish"
title = "Need for Fish"
author = "Steph"
value = 30
description = """The cats seem to really like fish, maybe if you [give](feed_me) them some they might give you something in return. """
tags = ["overflow"]
files = ["feed_me"]
flag = "flag{k1nd_f1sh}"
enabled = true
